version: "3"

services:
  chopshop_signin:
    container_name: chopshop_signin
    build:
      context: .
      network: host
    command: gunicorn --bind 0.0.0.0:8100 --workers 2 signinapp:app
    ports:
      - "8100:8100/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - './appdata:/appdata'
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
